### ISSUE TITLE
Version 1.2.0 not able to be downloaded/ crashes Minecraft

### ISSUE THREAD

**Issue by DisasterInbound** [itsmiir/tooltipsplus#1]
Hello, thank you for making and updating this mod.

I downloaded the recent 1.2.0 update but I experienced two things that I'm not sure if they are related.

1. I'm unable to download the mod through Modrinth. When I click on the Download button I get the following screen
![bkHuusU38yWKYaMN_2022-07-10_20-49-55](https://user-images.githubusercontent.com/64549167/178161674-ed54357f-a6ba-425d-8ca9-1f257d8f054c.png)

I had to right click the Download link and click on Save As.

2. The mod crashes Minecraft when starting it. This is the error log

> Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:146)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:146)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:210)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 11 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [E:\Games\MultiMC\instances\New Age\.minecraft\mods\Tooltips+ 1.2.0+1.19.jar]: java.util.zip.ZipException: zip END header not found
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:143)
	... 13 more
Caused by: java.lang.RuntimeException: Error analyzing [E:\Games\MultiMC\instances\New Age\.minecraft\mods\Tooltips+ 1.2.0+1.19.jar]: java.util.zip.ZipException: zip END header not found
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:255)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:212)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:280)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:250)
	... 7 more

**Comment by DisasterInbound** [comment]
Also, I can download and play with version 1.1.0 just fine.

**Comment by itsmiir** [comment]
pushed [v1.2.1+1.19](https://modrinth.com/mod/tooltipsplus/version/1.2.1) to modrinth. should fix both of those issues. thanks for letting me know!

**Comment by cCelectc** [comment]
@itsmiir It seems that [packwiz](https://github.com/packwiz/packwiz) cannot download [v1.2.1+1.19](https://modrinth.com/mod/tooltipsplus/version/1.2.1). There is the log.

> Download of Tooltips+ (tooltipsplus-1.2.1+1.19.jar) failed: failed to read file C:\Users\runneradmin\AppData\Local\packwiz\cache\bc\e99eae3ed1e029075dcf4b3e1ec3fe036865f9a2839e1227bac163c4637621 from cache: open C:\Users\runneradmin\AppData\Local\packwiz\cache\bc\e99eae3ed1e029075dcf4b3e1ec3fe036865f9a2839e1227bac163c4637621: The system cannot find the file specified.

And i'm sure the config file is correct.
```yml
name = "Tooltips+"
filename = "tooltipsplus-1.2.1+1.19.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/aYZWZvWI/versions/1.2.1/tooltipsplus-1.2.1%2B1.19.jar"
hash-format = "sha1"
hash = "ab352dac17b46b9233d54395e138fa98d155e6bd"

[update]
[update.modrinth]
mod-id = "aYZWZvWI"
version = "JVGdt32E"
```

**Comment by itsmiir** [comment]
@Cccc-owo this doesn't seem to be an issue with either the mod or modrinth; i used the same download url you did and downloaded and ran the mod without issue. i've never used packwiz, but the error seems to be unrelated to either.
